name: Pull request
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/reusable-verify.yaml
    secrets: inherit
